server:
  port: 9011
spring:
  application:
    name: manager-service #指定服务名
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6688/eureka/   ## 注册中心eurka地址
  instance:
    prefer-ip-address: true
zuul:
  routes:
    base-service:
      path: /base/**
      serviceId: base-service
    user-service:
      path: /user/**
      serviceId: user-service
    qa-service:
      path: /qa/**
      serviceId: qa-service
jwt:
  config:
    key: itcast
