server:
  port: 9003
spring:
  application:
    name: qa-service #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: czc121314
  jpa:
    database: MySQL
    show-sql: true

jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6688/eureka/   ## 注册中心eurka地址
  instance:
    prefer-ip-address: true
    ##.注册中心eurka地址
feign:
  hystrix:
    enabled: true

